apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: auth-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: node:20-alpine
          workingDir: /app
          command: ["sh", "-c", "npm install && npm run dev"]
          ports:
            - containerPort: 5173
          volumeMounts:
            - name: frontend-code
              mountPath: /app
      volumes:
        - name: frontend-code
          hostPath:
            path: /run/desktop/mnt/host/c/Users/mseke/Desktop/auth-By-PHP/frontend
            type: Directory
