apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: auth-app
type: Opaque
stringData:
  DB_DATABASE: laravel
  DB_USERNAME: laravel
  DB_PASSWORD: secret
  MYSQL_ROOT_PASSWORD: root
